name: "AIPriceAction Funds Data"

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

  # Sets up a scheduled run
  # schedule:
    # - cron: "0 0 * * *"
    # - cron: "0 5 * * *"
    # - cron: "0 9 * * *"

# Grant write permissions to the GITHUB_TOKEN to allow the workflow to commit and push changes.
permissions:
  contents: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    name: Get Funds Data

    steps:
      # Step 1: Check out the repository code so the workflow can access it.
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up the specific version of Python you are using.
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      # Step 3: Install the required Python libraries from your requirements file.
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Clean up old data and reports before the new run.
      - name: Clean up old data
        run: |
          # Remove old funds data to ensure we start fresh.
          rm -rf funds_data/*

      # Step 5: Run the Python script.
      - name: Run data 
        run: python get_fund_data.py

      # Step 6: Combine only the last 365 lines of each funds data file.
      - name: Combine last 365 lines of funds data
        run: |
          cd funds_data
          tail_output_file="funds_data.txt"

          if [ -f "$tail_output_file" ]; then
              rm "$tail_output_file"
          fi

          for file in *; do
              if [ -f "$file" ] && [ "$file" != "$tail_output_file" ]; then
                  full_path=$(pwd)/"$file"
                  echo "// $full_path" >> "$tail_output_file"
                  tail -n 365 "$file" >> "$tail_output_file"
                  echo "" >> "$tail_output_file"
              fi
          done

          echo "Last 365 lines of each file have been combined into $tail_output_file"

      # Step 7: Commit and push the updated report, data, and charts to the repository.
      - name: Commit and push changes
        run: |
          # Configure git with the details of the last commit's author to keep authorship consistent.
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

          # Add all new/changed files to the staging area.
          git add .

          # Check if there are any changes to commit. If not, exit successfully.
          if git diff-index --quiet HEAD; then
            echo "No changes to commit. Exiting."
            exit 0
          fi

          # Amend the last commit to avoid polluting the git history with weekly update commits.
          git commit --amend --no-edit

          # Force push the amended commit to the repository.
          # --force-with-lease is a safer alternative to a standard --force.
          git push --force-with-lease

